### ISSUE TITLE
GKE API changes - automatic upgrades and repairs

### ISSUE THREAD

**Issue by errordeveloper** [isovalent/gke-test-cluster-operator#11]
Looks like there were API changes in GKE and automatic upgrades and rapair are now required in regular release channel...

Here's an example:

```YAML
apiVersion: clusters.ci.cilium.io/v1alpha2
kind: TestClusterGKE
metadata:
  creationTimestamp: "2021-02-03T02:17:46Z"
  generation: 1
  name: test-66gx7
  namespace: test-clusters
  resourceVersion: "155013016"
  selfLink: /apis/clusters.ci.cilium.io/v1alpha2/namespaces/test-clusters/testclustersgke/test-66gx7
  uid: acd5f665-2fd6-4bc2-b401-417227e5ce91
spec:
  configTemplate: basic
  jobSpec:
    runner:
      command:
      - /usr/local/bin/cilium-test-gke.sh
      - quay.io/cilium/cilium:latest
      - quay.io/cilium/operator-generic:latest
      - quay.io/cilium/hubble-relay:latest
      - NightlyPolicyStress
      image: cilium/cilium-test-dev:7cdf8024e
      initImage: quay.io/isovalent/gke-test-cluster-initutil:854733411778d633350adfa1ae66bf11ba658a3f
  location: europe-west2-b
  machineType: n1-standard-4
  nodes: 2
  project: cilium-ci
  region: europe-west2
status:
  clusterName: test-66gx7-c5lsf
  conditions:
  - lastTransitionTime: "2021-02-03T16:52:07Z"
    message: Some dependencies are not ready yet
    reason: DependenciesNotReady
    status: "False"
    type: Ready
  dependencyConditions:
    ContainerCluster:test-clusters/test-66gx7-c5lsf:
    - lastTransitionTime: "2021-02-03T16:52:07Z"
      message: The resource is up to date
      reason: UpToDate
      status: "True"
      type: Ready
    ContainerNodePool:test-clusters/test-66gx7-c5lsf:
    - lastTransitionTime: "2021-02-03T02:17:46Z"
      message: 'Update call failed: error applying desired state: summary: error creating
        NodePool: googleapi: Error 400: Auto_upgrade and auto_repair cannot be false
        when release_channel REGULAR is set., badRequest, detail: '
      reason: UpdateFailed
      status: "False"
      type: Ready
```

Originally this was intentional, as actually for testing purposes it's best to have these features disable.

**Comment by errordeveloper** [comment]
We need to review what other release channels do, ideally we should use a channel that is as close to regular channel as possible. Also, channel and version still need to be exposed via the API.

**Comment by errordeveloper** [comment]
If using different channel is not an option, automatic upgrades maybe not a hard bullet to bite, and I believe GKE allowed specifying maintenance window, but that needs checking. Automatic repairs is one that would worry me more, as it might interfere with tests, most like it will prevent chaos testing outright. More analysis of the implementation features would help, perhaps there is a way to suspend repairs.

**Comment by errordeveloper** [comment]
With regards to changing this, the configuration is defined here:

https://github.com/isovalent/gke-test-cluster-operator/blob/a6824ed4a47b5c0f78b1aefccfda39c7ef363b7e/config/templates/basic/basic.cue#L60-L63

**Comment by fristonio** [comment]
So I briefly looked at this auto repair and auto upgrade issue. As far as I can understand enabling both can affect our test in some way but the probability of that happening is not very high.

* **Auto repair**
Nodes are auto repaired(drained and restarted) if they report `NotReady` status for more than 10 minutes. This can happen if Cilium in some configuration/test somehow makes the node not ready. There is a way to disable this for the existing node pool using `gcloud` and I assume it works for all release channels. I wonder why we get an error when we set this to false in our config connector configuration.

* **Auto upgrade**
Nodes k8s version are automatically upgraded(this can be both patch and minor version). There is a way we can make sure auto-upgrade does not happen during our tests. This is by setting a maintenance window that is out of the duration of our tests(https://cloud.google.com/kubernetes-engine/docs/how-to/maintenance-windows-and-exclusions). Not sure if we can do this with the config connector though.

**Comment by errordeveloper** [comment]
@fristonio thanks for looking into this!

> I wonder why we get an error when we set this to false in our config connector configuration.

The issue is that the API stated requiring both of these fields to be set to `true` when _stable release channel_ is used.

> This is by setting a maintenance window that is out of the duration of our tests. Not sure if we can do this with the config connector though.

This is definitely something we can specify in [`ContainerCluster` object](https://cloud.google.com/config-connector/docs/reference/resource-docs/container/containercluster):

```yaml
  maintenancePolicy:
    dailyMaintenanceWindow:
      duration: string
      startTime: string
    maintenanceExclusion:
    - endTime: string
      exclusionName: string
      startTime: string
    recurringWindow:
      endTime: string
      recurrence: string
      startTime: string
```
